version: "3"
services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=Hanying
      - CHOKIDAR_USEPOLLING=true
      # env_file:
      # - ./.env